### ISSUE TITLE
Transfer Money

### ISSUE THREAD

**Issue by agicitag** [agicitag/BCTweaks#12]
Create a `/sendMoney <Player> <Amount>` command that sends the given player money.
The following steps need to be done:
- [x] Create the command
- [x] Only subtract the money from the sending player after the other confirms they reveived it
- [x] Let the receiving person accept/decline

**Comment by agicitag** [comment]
Accepting/Declining brings a whole load of problems like:
- What if the sending person left before accepting
- What if multiple people send offers before accepting

The way easier way is to just allow whitelisted friends to send money

**Comment by crimsontropy** [comment]
Done in 3ad0c84
