### ISSUE TITLE
BUG: `TypeError` when a BCT user enters the room

### ISSUE THREAD

**Issue by bananarama92** [agicitag/BCTweaks#41]
Stumbled upon a `TypeError` when another BCT user entered the room. 
It doesn't seem to be very consist, but I do recall seeing similar messages before:
```
16:11:47.888 BCX: Loaded character AlterTerra (78306)                            characters.ts:66:10
16:11:48.047 Error parsing BCT Message from: AlterTerra.                         bct.js:288:15
16:11:48.047 TypeError: sender.BCT is undefined                                  bct.js:289:15
    parseMessage https://agicitag.github.io/BondageClubTools/extension/bct.js:273
```

See below for the referenced code.

Could it be that the `BCT_MSG_INITILIZATION_SYNC` code branch is hit before `BCT_MSG_ACTIVITY_AROUSAL_SYNC` here? There has been a fairly big overhaul of the chat message system recently ([BondageProjects/Bondage-College#3592](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/3592)), so I wonder if it could be related?
 https://github.com/agicitag/BondageClubTools/blob/3e6c0cad5d1a78c68d4181c882f5b33d4c14db1a/extension/bct.js#L260-L285

**Comment by crimsontropy** [comment]
The `BCT_MSG_INITILIZATION_SYNC` is meant to be hit before `BCT_MSG_ACTIVITY_AROUSAL_SYNC` so possibly the opposite is happening? Julia would have to look into that. 
The changes in ChatRoomMessage shouldn't affect here as far as I can tell. It has only changed how the game parses the message and didn't really change the message itself. 
What I think has happened is that, something triggered `BCT_MSG_ACTIVITY_AROUSAL_SYNC` as soon as Terra entered the room and although `BCT_MSG_INITILIZATION_SYNC` was sent first, Rama received the arousal sync before. Would also explain why it is so rare to trigger.
So maybe waiting for initialization message before parsing other BCT messages should fix it.

**Comment by agicitag** [comment]
Ah yeah, that bug has been there from the very beginning. It happens rarely after a server disconnect and gets fixed after a reload. I tried a couple times but havent found a way to fix it yet, as its very hard to test it, if it only occurs rarely after a server disconnect.

**Comment by Shiranui-Izayoi** [comment]
Just letting you know I seem to be able to reproduce it fairly consistently if I have the auto remake and rejoin rooms setting active. Even more so if that room has a custom background.

Also it seems that closing the tab instead of going back to the main hall and leaving that way will make it even more consistent in showing up.
