### ISSUE TITLE
BUG: Invalid variable name in the `beta` branch

### ISSUE THREAD

**Issue by bananarama92** [agicitag/BCTweaks#47]
Seems to be a typo in the `beta` branch, referencing a non-existant `CharaChatRoomCharactercter` variable rather than `ChatRoomCharacter`.

https://github.com/agicitag/BCTweaks/blob/fab05bdc58c43e67f4b50fa36cbd5011799edd79/extension/bct.js#L1462

**Comment by crimsontropy** [comment]
Huh., this typo has been there since December. I'll push a fix.

**Comment by crimsontropy** [comment]
the commit [1d8d379 ](https://github.com/agicitag/BCTweaks/commit/1d8d37987434dab3711526895bd4d9342e950d86) fixes the issue
