### ISSUE TITLE
BC `ControllerActive` variable removed as of R92Beta1

### ISSUE THREAD

**Issue by bananarama92** [agicitag/BCTweaks#49]
Just a heads up: the `ControllerActive` has been remove from the current BC master branch, being replaced with the new `ControllerIsActive()` function (so BCT will, in its current state, break as of R92Beta1 or later).

For reference: the patch I used for MBS for dealing with the same issue: https://github.com/bananarama92/MBS/commit/b974b31be5e3039d311c3991accfbc5835d08c13.

**Comment by crimsontropy** [comment]
Fixed in [commit](https://github.com/agicitag/BCTweaks/commit/2339769453dbe2f190c291a653ea269c1da49383)
