### ISSUE TITLE
R91 broken with current updates

### ISSUE THREAD

**Issue by Drakonas** [agicitag/BCTweaks#50]
Running this script in its current state causes anyone using R91 to have a timing issue or possible memory leak. The UI starts lagging drastically after minutes of use.

I tested with only BCTweaks Loader enabled. Problem occurs within a few minutes after perusing menus on my character.

With BCTweaks disabled and everything else either enabled or disabled, no issues.

I recommend users avoid BCTweaks if you're on R91 and are experiencing lag currently.

I've confirmed with 3 others that they have lag with BCTweaks enabled on R91, and disabling it fixes the lag. Updating to R92 beta also reportedly fixes the issue.

The issue is BCTweaks updated for R92. EIther due to the update it had to make to change some functions to match the function name changes, or the Processor timing fix. A wrapper could be suggested to be placed to check for the Bondage Club version around these two points in the code, so the older code still loads for R91.

However, that's extra uneccessary work. R92 is on the rise, so I'm mainly making this post to warn people to just not use BCTweaks on Public BC until R92 releases, then I'll close the issue.

**Comment by crimsontropy** [comment]
R92 released.
