### ISSUE TITLE
Add different "role?" to have option for someone to see my room, but don't using BF lock.

### ISSUE THREAD

**Issue by dDeepLb** [agicitag/BCTweaks#51]

**Comment by crimsontropy** [comment]
I think you can set the lock to whitelist only and keep your best friends out of your whitelist to block them from using the lock.

**Comment by dDeepLb** [comment]
what if i'm on extreme?🧐

**Comment by crimsontropy** [comment]
I didn't think of that. I'll try to implement something but adding a new role entirely doesn't sound good.. idk.
Something like disabling bf lock access for a particular best friend in friendlist?

**Comment by dDeepLb** [comment]
or just add config to whitelist who can or can't use BF locks or see your room. just like it was made in LSCG.

**Comment by crimsontropy** [comment]
I've added a new setting in 05f4523 where you can add those who you just wanna share rooms with.
