### ISSUE TITLE
Menu button hitbox fix is now redundant

### ISSUE THREAD

**Issue by bananarama92** [agicitag/BCTweaks#52]
Apparently this fix got implemented in BC like... 6 months ago in [`BondageProjects/Bondage-College@19de988b`](https://gitgud.io/BondageProjects/Bondage-College/-/commit/19de988bb01ea1eee08be2b96f8ec23302acb36a#72afe1d8439fbc112ea52bf82a0e1b810ceb604d_878_916). I'd suggest removing it at this point, especially since I found out the hard way that the failure of the respective `PreferenceClick()` hook to call `next()` (when the fix is enabled) breaks any lower-priority hooks.

**Comment by crimsontropy** [comment]
Oof.. got it.

**Comment by crimsontropy** [comment]
Removed in beta 0.6.3
