### ISSUE TITLE
ideas for transfer money solutions

### ISSUE THREAD

**Issue by meandred** [agicitag/BCTweaks#53]
for the what if person who offered leaves issue: how about if leaves that declines automatically

for multiple people offers: how about a text block appears saying to the people past the 1st the person in question is busy atm and can't process the offer

**Comment by crimsontropy** [comment]
There's a two generals type of problem here. Consider person A sends 10$ to person B but before person B accepts, person A disconnects/leaves the room. Now if the money got deducted from person A and person B has rejected- the 10$ goes into the void. I could put a warning to not leave the room before you get the received/rejected money acknowledgement, which is probably what I'm gonna do.

**Comment by crimsontropy** [comment]
That leads to infinite money glitch~ Person A sends money and leaves before confirmation, so they don't lose any money. 
I'd rather have Person A getting penalty for leaving the room, then create more money.

**Comment by crimsontropy** [comment]
Completed the feature in 3ad0c84 but I'll keep this issue up for any bugs that show up in beta. I went with Rama and Julia's suggestion of deducting the money after person B sends some confirmation.

**Comment by crimsontropy** [comment]
Released to main version
