### ISSUE TITLE
lock's bugged

### ISSUE THREAD

**Issue by Powerkhan** [agicitag/BCTweaks#56]
for some reason when trying to set BF locks to who is allowed to use it, this error pops up in a crash report. BF locks and timered can no longer be used.
it seems like .Name is not pointing to anything and is being erased and erroring out. shouldn't it point to something like Property.LockMemberNumber instead? i know high sec locks allow for a whitelist and supposedily if you are someone's BF added you should technically be allowed to see them on it. otherwise it just becomes an unpickable high-sec lock (as intended) by anywho who isn't on the list as such. any suggestions or probable causes that conflict with another addon? 

----- UNHANDLED ERROR (IN BCTweaks) -----
Message: Script error.
Source: :0:0
null

----- Current context (most recent first) -----
> Function DialogItemClick hook from BCTweaks
> Function DialogItemClick hook from BCX
> Function DialogItemClick hook from BCX
> Function DialogItemClick hook from BCX
> Function DialogClick hook chain exit
> Function DialogClick hook from LSCG
> Function DialogClick hook from EBCH
> Function DialogClick hook from LSCG
> Function DialogClick hook from FBC
> Function CommonClick hook chain exit
> Function CommonClick hook from FBC
> Function CommonClick hook from UniRemote
[unknown origin]

----- Debug report -----
Location: https://www.bondageprojects.elementfx.com/R100/BondageClub/
BC Version: R100
ModSDK Version: 1.1.0
Mods:
  - For Better Club (FBC): 4.79
    repository: https://gitlab.com/Sidiousious/bce.git
  - Eli's Bondage Club Helper (EBCH): 1.02.40
    repository: https://gitlab.com/e2466/ebch
  - Bondage Club Mod (BCMod): 0.1
  - Bondage Club Auto React + (BCAR+): 0.7.5
    repository: https://github.com/DrBranestawm/BCAR
  - Little Sera's Club Games (LSCG): 0.3.44
    repository: https://github.com/littlesera/LSCG
  - Advanced Drone Control System (Advanced Drone Control System): 0.7.10
    repository: https://gitlab.com/dynilath/BCADCS
  - BondageClub Responsive (BondageClub Responsive): 1.0.4
    repository: https://github.com/dynilath/BCResponsive
  - Mute's Bondage Club Hacks Collection (MBCHC): dev.8
    repository: https://code.fleshless.org/mute/MBCHC/
  - Fantastic Ultimate Solution to Addon Management (FUSAM): 1e0cc10c
    repository: https://gitlab.com/Sidiousious/bc-addon-loader
  - Bondage Club Tweaks (BCTweaks): 0.6.0
    repository: https://github.com/agicitag/BCTweaks
  - Universal Remote (UniRemote): 7d688a01
    repository: https://gitlab.com/sidiousious/universal-remote
  - Bondage Club Extended (BCX): 0.9.9-a8f7a83f
    repository: https://github.com/Jomshir98/bondage-club-extended
  - Maid's Bondage Scripts (MBS): 1.3.0
    repository: https://github.com/bananarama92/MBS
  - BCX Reset Button Disabler (BRBD): 1.0.0
    repository: https://github.com/ciberweaboo/brbd
  - BC Themed (Themed): 1.1.0
    repository: https://github.com/dDeepLb/Themed-BC
  - Notify Plus (Notify Plus): 0.3.2
  - TTS for chat and vibrations of all mediums (TTS): 1.0.4
    repository: https://gitlab.com/KatKammand/tts
  - Ultra Bondage Club (ULTRAbc): 2.6
    repository: https://github.com/tetris245/ULTRAbc
Detected legacy mods (NOT USING ModSDK):
  - BondageClubTools
  - Moaner: false

**Comment by crimsontropy** [comment]
Sorry for the late response, I haven't paid much attention to this addon in a while. I'll try looking into this issue.

**Comment by crimsontropy** [comment]
Unfortunately there isn't much I could do in this case. The underlying lock that BF lock modifies is the high-sec lock, which means you need to have the permission for high-sec locks available to be able to use BF locks.

**Comment by Powerkhan** [comment]
no i understand that and no worries about the late or long time for the reply. for clarification:

me and the other party both have high-sec locks enabled.
both of us are added as BF's
we were able to lock ourselves with it, and the functionality of someone without being a BF added shows correctly as the tumbler offsetting and having unbreakable styled latches.

we could not however access adding the lock to another (outside of setting it as a custom item) but the tumbler still shows as if we aren't BF's therefore unpickable.
the timer lock as well even when added on ourselves or others through a custom item does not allow for those listed or anyone to also modify the timers on them.

unfortunately i think this part would need a top down rework. 🙁

BTW this is Pk! hugs.​ 😄
________________________________
